package com.imooc.po;

import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   轮播图 
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table carousel
 */
public class Carousel {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.id
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    private String id;

    /**
     * Database Column Remarks:
     *   图片 图片地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.image_url
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    private String imageUrl;

    /**
     * Database Column Remarks:
     *   背景色
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.background_color
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    private String backgroundColor;

    /**
     * Database Column Remarks:
     *   商品id 商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.item_id
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    private String itemId;

    /**
     * Database Column Remarks:
     *   商品分类id 商品分类id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.cat_id
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    private String catId;

    /**
     * Database Column Remarks:
     *   轮播图类型 轮播图类型，用于判断，可以根据商品id或者分类进行页面跳转，1：商品 2：分类
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.type
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    private Integer type;

    /**
     * Database Column Remarks:
     *   轮播图展示顺序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.sort
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    private Integer sort;

    /**
     * Database Column Remarks:
     *   是否展示
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.is_show
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    private Integer isShow;

    /**
     * Database Column Remarks:
     *   创建时间 创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.create_time
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    private LocalDateTime createTime;

    /**
     * Database Column Remarks:
     *   更新时间 更新
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.update_time
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    private LocalDateTime updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.id
     *
     * @return the value of carousel.id
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.id
     *
     * @param id the value for carousel.id
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.image_url
     *
     * @return the value of carousel.image_url
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.image_url
     *
     * @param imageUrl the value for carousel.image_url
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.background_color
     *
     * @return the value of carousel.background_color
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    public String getBackgroundColor() {
        return backgroundColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.background_color
     *
     * @param backgroundColor the value for carousel.background_color
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    public void setBackgroundColor(String backgroundColor) {
        this.backgroundColor = backgroundColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.item_id
     *
     * @return the value of carousel.item_id
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.item_id
     *
     * @param itemId the value for carousel.item_id
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    public void setItemId(String itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.cat_id
     *
     * @return the value of carousel.cat_id
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    public String getCatId() {
        return catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.cat_id
     *
     * @param catId the value for carousel.cat_id
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    public void setCatId(String catId) {
        this.catId = catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.type
     *
     * @return the value of carousel.type
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.type
     *
     * @param type the value for carousel.type
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.sort
     *
     * @return the value of carousel.sort
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.sort
     *
     * @param sort the value for carousel.sort
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.is_show
     *
     * @return the value of carousel.is_show
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    public Integer getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.is_show
     *
     * @param isShow the value for carousel.is_show
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    public void setIsShow(Integer isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.create_time
     *
     * @return the value of carousel.create_time
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.create_time
     *
     * @param createTime the value for carousel.create_time
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.update_time
     *
     * @return the value of carousel.update_time
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.update_time
     *
     * @param updateTime the value for carousel.update_time
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Carousel other = (Carousel) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getImageUrl() == null ? other.getImageUrl() == null : this.getImageUrl().equals(other.getImageUrl()))
            && (this.getBackgroundColor() == null ? other.getBackgroundColor() == null : this.getBackgroundColor().equals(other.getBackgroundColor()))
            && (this.getItemId() == null ? other.getItemId() == null : this.getItemId().equals(other.getItemId()))
            && (this.getCatId() == null ? other.getCatId() == null : this.getCatId().equals(other.getCatId()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getSort() == null ? other.getSort() == null : this.getSort().equals(other.getSort()))
            && (this.getIsShow() == null ? other.getIsShow() == null : this.getIsShow().equals(other.getIsShow()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Fri Nov 06 16:34:48 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getImageUrl() == null) ? 0 : getImageUrl().hashCode());
        result = prime * result + ((getBackgroundColor() == null) ? 0 : getBackgroundColor().hashCode());
        result = prime * result + ((getItemId() == null) ? 0 : getItemId().hashCode());
        result = prime * result + ((getCatId() == null) ? 0 : getCatId().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getSort() == null) ? 0 : getSort().hashCode());
        result = prime * result + ((getIsShow() == null) ? 0 : getIsShow().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}